package com.kntransport.app.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.time.LocalDate
import java.time.format.DateTimeFormatter

data class FinancialReportData(
    val period       : String,
    val totalRevenue : String,
    val collected    : String,
    val outstanding  : String,
    val routes       : List<RouteEntry>,
    val transactions : List<TransactionEntry>,
)

data class RouteEntry(val route: String, val amount: String)
data class TransactionEntry(val commuter: String, val route: String, val amount: String, val date: String, val paid: Boolean)

object ReportExporter {

    private val dateStamp get() = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))

    fun sharePdf(context: Context, data: FinancialReportData) {
        val file = buildPdf(context, data)
        launchShareIntent(context, file, "application/pdf")
    }

    fun shareCsv(context: Context, data: FinancialReportData) {
        val file = buildCsv(context, data)
        launchShareIntent(context, file, "text/csv")
    }

    fun shareViaEmail(context: Context, data: FinancialReportData) {
        val csv  = buildCsv(context, data)
        val uri  = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", csv)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type         = "message/rfc822"
            putExtra(Intent.EXTRA_EMAIL,   arrayOf("info@mrhdigital.co.za"))
            putExtra(Intent.EXTRA_SUBJECT, "K&T Transport Financial Report — ${data.period}")
            putExtra(Intent.EXTRA_TEXT,
                "Please find attached the K&T Transport financial report for ${data.period}.\n\n" +
                "Total Revenue : ${data.totalRevenue}\n" +
                "Collected     : ${data.collected}\n" +
                "Outstanding   : ${data.outstanding}\n\n" +
                "Generated by K&T Transport Admin App."
            )
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Send report via email"))
    }

    private fun buildPdf(context: Context, data: FinancialReportData): File {
        val doc     = PdfDocument()
        val pageW   = 595   // A4 width in points
        val pageH   = 842   // A4 height in points
        val page    = doc.startPage(PdfDocument.PageInfo.Builder(pageW, pageH, 1).create())
        val canvas  = page.canvas

        val boldPaint = Paint().apply { color = Color.BLACK; textSize = 14f; isFakeBoldText = true }
        val bodyPaint = Paint().apply { color = Color.DKGRAY; textSize = 11f }
        val dimPaint  = Paint().apply { color = Color.GRAY;   textSize = 10f }
        val headPaint = Paint().apply { color = Color.BLACK;  textSize = 20f; isFakeBoldText = true }
        val accentPaint = Paint().apply { color = Color.parseColor("#E8C14A"); textSize = 12f; isFakeBoldText = true }
        val linePaint = Paint().apply { color = Color.LTGRAY; strokeWidth = 1f }

        var y = 60f

        // Header
        canvas.drawText("K&T Transport", 40f, y, headPaint); y += 28f
        canvas.drawText("Financial Report — ${data.period}", 40f, y, bodyPaint); y += 16f
        canvas.drawText("Generated: $dateStamp", 40f, y, dimPaint); y += 20f
        canvas.drawLine(40f, y, (pageW - 40).toFloat(), y, linePaint); y += 20f

        // Summary
        canvas.drawText("SUMMARY", 40f, y, boldPaint); y += 20f
        canvas.drawText("Total Revenue", 40f, y, dimPaint)
        canvas.drawText(data.totalRevenue, 200f, y, accentPaint); y += 16f
        canvas.drawText("Collected",      40f, y, dimPaint)
        canvas.drawText(data.collected,   200f, y, bodyPaint.apply { color = Color.parseColor("#4CAF50") }); y += 16f
        canvas.drawText("Outstanding",    40f, y, dimPaint)
        canvas.drawText(data.outstanding, 200f, y, bodyPaint.apply { color = Color.parseColor("#E85C2A") }); y += 24f
        canvas.drawLine(40f, y, (pageW - 40).toFloat(), y, linePaint); y += 20f

        // Routes
        bodyPaint.apply { color = Color.DKGRAY }
        canvas.drawText("REVENUE BY ROUTE", 40f, y, boldPaint); y += 20f
        data.routes.forEach { r ->
            canvas.drawText(r.route,  40f,  y, bodyPaint)
            canvas.drawText(r.amount, 420f, y, accentPaint.apply { color = Color.parseColor("#E8C14A") })
            y += 16f
        }
        y += 12f
        canvas.drawLine(40f, y, (pageW - 40).toFloat(), y, linePaint); y += 20f

        // Transactions
        canvas.drawText("TRANSACTIONS", 40f, y, boldPaint); y += 18f
        dimPaint.apply { isFakeBoldText = true }
        canvas.drawText("Commuter",  40f,  y, dimPaint)
        canvas.drawText("Route",     180f, y, dimPaint)
        canvas.drawText("Amount",    360f, y, dimPaint)
        canvas.drawText("Date",      430f, y, dimPaint)
        canvas.drawText("Status",    490f, y, dimPaint)
        y += 14f
        canvas.drawLine(40f, y, (pageW - 40).toFloat(), y, linePaint); y += 12f
        dimPaint.apply { isFakeBoldText = false }

        data.transactions.forEach { tx ->
            canvas.drawText(tx.commuter, 40f,  y, bodyPaint)
            canvas.drawText(tx.route,    180f, y, bodyPaint)
            canvas.drawText(tx.amount,   360f, y, bodyPaint)
            canvas.drawText(tx.date,     430f, y, bodyPaint)
            val statusPaint = Paint().apply {
                textSize = 10f
                color    = if (tx.paid) Color.parseColor("#4CAF50") else Color.parseColor("#E85C2A")
            }
            canvas.drawText(if (tx.paid) "Paid" else "Pending", 490f, y, statusPaint)
            y += 16f
        }

        y += 20f
        canvas.drawLine(40f, y, (pageW - 40).toFloat(), y, linePaint); y += 16f
        canvas.drawText("K&T Transport · info@mrhdigital.co.za", 40f, y, dimPaint)

        doc.finishPage(page)

        val dir  = File(context.cacheDir, "reports").also { it.mkdirs() }
        val file = File(dir, "knt_financials_${data.period.replace(" ", "_")}_$dateStamp.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file
    }

    private fun buildCsv(context: Context, data: FinancialReportData): File {
        val sb = StringBuilder()
        sb.appendLine("K&T Transport Financial Report")
        sb.appendLine("Period,${data.period}")
        sb.appendLine("Generated,$dateStamp")
        sb.appendLine()
        sb.appendLine("SUMMARY")
        sb.appendLine("Total Revenue,${data.totalRevenue}")
        sb.appendLine("Collected,${data.collected}")
        sb.appendLine("Outstanding,${data.outstanding}")
        sb.appendLine()
        sb.appendLine("REVENUE BY ROUTE")
        sb.appendLine("Route,Amount")
        data.routes.forEach { sb.appendLine("\"${it.route}\",${it.amount}") }
        sb.appendLine()
        sb.appendLine("TRANSACTIONS")
        sb.appendLine("Commuter,Route,Amount,Date,Status")
        data.transactions.forEach {
            sb.appendLine("\"${it.commuter}\",\"${it.route}\",${it.amount},${it.date},${if (it.paid) "Paid" else "Pending"}")
        }

        val dir  = File(context.cacheDir, "reports").also { it.mkdirs() }
        val file = File(dir, "knt_financials_${data.period.replace(" ", "_")}_$dateStamp.csv")
        file.writeText(sb.toString())
        return file
    }

    private fun launchShareIntent(context: Context, file: File, mimeType: String) {
        val uri    = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "K&T Transport Financial Report")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share report via"))
    }
}
